import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { clsx } from "clsx";
import Header from "./_components/header";
import Footer from "./_components/footer";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-full">
      <body
        className={clsx(
          inter.className,
          "min-h-full",
          "flex",
          "flex-col",
          "bg-teal-500"
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
